apiVersion: v1
kind: apiVersion: v1
kind: ConfigMap
metadata:
  name: api-configs
  namespace: default
data:
  application.properties: |
    jdbc.datasource-proxy.json-format=true
    jdbc.datasource-proxy.query.enable-logging=true
    jdbc.datasource-proxy.query.log-level=DEBUG