apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api
  namespace: default
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: microservice
      app.kubernetes.io/name: api
