apiVersion: v1
kind: Service

metadata:
  name: api
  namespace: default

spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 8082
      protocol: TCP
      targetPort: metrics

  selector:
    app.kubernetes.io/name: api
    app.kubernetes.io/component: microservice