apiVersion: v1
kind: Service

metadata:
  name: webhook
  namespace: cloud-diplomats

spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 8082
      protocol: TCP
      targetPort: metrics

  selector:
    app.kubernetes.io/component: microservice
    app.kubernetes.io/name: webhook