apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: webhook
  namespace: cloud-diplomats
  labels:
    prometheus.io/scrap-with: kube-prometheus-stack
spec:
  endpoints:
    - interval: 30s
      port: metrics
      path: /actuator/prometheus
      relabelings:
        - sourceLabels: [__meta_kubernetes_service_label_app_kubernetes_io_application]
          targetLabel: application
        - sourceLabels: [__meta_kubernetes_service_label_app_kubernetes_io_component]
          targetLabel: component
        - sourceLabels: [__meta_kubernetes_service_label_app_kubernetes_io_managed_by]
          targetLabel: managed_by
  namespaceSelector:
    matchNames:
      - cloud-diplomats

  selector:
    matchLabels:
    app.kubernetes.io/application: cloud-diplomats-webhook
    app.kubernetes.io/component: worker
