apiVersion: v1
kind: Service

metadata:
  name: webhook
  namespace: cloud-diplomats
  labels:
    app.kubernetes.io/application: cloud-diplomats-webhook
    app.kubernetes.io/component: worker
    app.kubernetes.io/managed-by: Jonathan

spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 8082
      protocol: TCP
      targetPort: metrics

  selector:
    app.kubernetes.io/application: cloud-diplomats-webhook
    app.kubernetes.io/component: worker