apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-diplomats-api
  namespace: cloud-diplomats
  labels:
    app.kubernetes.io/instance: cloud-diplomats-app
    app.kubernetes.io/name: cloud-diplomats-api
    app.kubernetes.io/managed-by: Jonathan
data:
  HTTP_CLIENTS_MY_EXTERNAL_API_BASE_URL: "https://webhook.site/f6ec3af8-08d7-427d-b839-3d88f84fa9c0"
  
  # add span attribute "jdbc.params[0]" with all value
  # JDBC_DATASOURCE_PROXY_INCLUDE_PARAMETER_VALUES: "false"
  # JDBC_INCLUDES: "QUERY,FETCH" # can remove CONNECTION if too many traces