apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-diplomats-api
  namespace: cloud-diplomats
  labels:
    app.kubernetes.io/instance: cloud-diplomats-app
    app.kubernetes.io/application: cloud-diplomats-api
    app.kubernetes.io/managed-by: Jonathan
data:
  HTTP_CLIENTS_MY_EXTERNAL_API_BASE_URL: "https://webhook.site/c926ec6d-4ba5-41ca-bceb-0d06643cafe4"
  
  
  # MANAGEMENT_ENDPOINT_HEALTH_GROUP_READINESS_INCLUDE: "rabbit"
  # add span attribute "jdbc.params[0]" with all value
  # JDBC_DATASOURCE_PROXY_INCLUDE_PARAMETER_VALUES: "false"
  # JDBC_INCLUDES: "QUERY,FETCH" # can remove CONNECTION if too many traces

  # OTEL configuration
  OTEL_INSTRUMENTATION_RUNTIME_TELEMETRY_EMIT_EXPERIMENTAL_TELEMETRY: "true"
  OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_LOG_ATTRIBUTES: "true"
  OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_CAPTURE_CODE_ATTRIBUTES: "true"
  OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_CAPTURE_MARKER_ATTRIBUTE: "true"
  OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_CAPTURE_KEY_VALUE_PAIR_ATTRIBUTES: "true"
  OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_CAPTURE_LOGGER_CONTEXT_ATTRIBUTES: "true"

