apiVersion: v1
kind: ConfigMap
metadata:
  name: api-configs
  namespace: cloud-diplomats
data:
  HTTP_CLIENTS_MY_EXTERNAL_API_BASE_URL: aHR0cHM6Ly93ZWJob29rLnNpdGUvYjRiNDNkYmQtOTk4MC00NjkwLThkYjctZTUwYmU2NmU0ZDBj

  # tracing
  jdbc.datasource-proxy.include-parameter-values: "true"
  jdbc.includes: "QUERY, FETCH"