apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-diplomats-api
  namespace: cloud-diplomats
  labels:
    app.kubernetes.io/instance: cloud-diplomats-app
    app.kubernetes.io/component: api
    app.kubernetes.io/application: cloud-diplomats-api
    app.kubernetes.io/managed-by: Jonathan
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: cloud-diplomats-app
      app.kubernetes.io/component: api
      app.kubernetes.io/application: cloud-diplomats-api
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: cloud-diplomats-app
        app.kubernetes.io/component: api
        app.kubernetes.io/application: cloud-diplomats-api
    spec:
      serviceAccountName: spring-namespace-reader
      containers:
        - name: api
          image: jojoooo1/api:14.0-otel
          env:
            - name: "MANAGEMENT_SERVER_PORT"
              value: "8081"
            - name: "JAVA_TOOL_OPTIONS"
              value: "-javaagent:/workspace/opentelemetry/opentelemetry-javaagent.jar"
            - name: "OTEL_JAVAAGENT_CONFIGURATION_FILE"
              value: "/workspace/opentelemetry/default.properties"
            - name: "OTEL_METRICS_EXPORTER"
              value: "otlp"
            # https://github.com/open-telemetry/semantic-conventions/blob/main/model/metrics/jvm-metrics-experimental.yaml
            - name: "OTEL_INSTRUMENTATION_RUNTIME_TELEMETRY_EMIT_EXPERIMENTAL_TELEMETRY"
              value: "true"
            - name: "OTEL_EXPORTER_OTLP_METRICS_ENDPOINT"
              value: "http://otel-collector-metrics-collector.observability:4317"

            # - name: "OTEL_TRACES_EXPORTER"
            #   value: "otlp"
            # - name: "OTEL_EXPORTER_OTLP_TRACES_ENDPOINT"
            #   value: "http://otel-collector-traces-collector.observability:4317"

            # Needed when database schema is not empty
            - name: "SPRING_FLYWAY_BASELINE_ON_MIGRATE"
              value: "true"

          envFrom:
            - configMapRef:
                name: cloud-diplomats-api
            - secretRef:
                name: cloud-diplomats-api

          ports:
            - name: container-port
              containerPort: 8080
            - name: metrics
              containerPort: 8081

          readinessProbe:
            initialDelaySeconds: 15
            periodSeconds: 10
            httpGet:
              path: /actuator/health/readiness
              port: metrics
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: metrics
            initialDelaySeconds: 15
            periodSeconds: 10

          lifecycle:
            preStop:
              httpGet:
                path: actuator/preStopHook/10000
                port: metrics

          # resources:
          #   requests:
          #     memory: 768Mi
          #     cpu: 500m
          #   limits:
          #     memory: 768Mi

          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp

          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL

      # Necessary for readOnly system
      volumes:
        - name: tmp-volume
          emptyDir: {}    