apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api
  namespace: cloud-diplomats
  
  labels:
    prometheus.io/scrap-with: kube-prometheus-stack
spec:
  endpoints:
    - interval: 30s
      port: metrics
      path: /actuator/prometheus
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
          targetLabel: name
        - sourceLabels: [__meta_kubernetes_pod_label_app_kubernetes_io_component]
          targetLabel: component
        - sourceLabels: [__meta_kubernetes_pod_label_app_kubernetes_io_managed_by]
          targetLabel: managedBy

  namespaceSelector:
    matchNames:
      - cloud-diplomats

  selector:
    matchLabels:
      app.kubernetes.io/name: cloud-diplomats-api
      app.kubernetes.io/component: api