apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api
  namespace: cloud-diplomats
  
  labels:
    prometheus.io/scrap-with: kube-prometheus-stack
spec:
  endpoints:
    - interval: 30s
      port: metrics
      path: /actuator/prometheus

  namespaceSelector:
    matchNames:
      - cloud-diplomats
  selector:
    matchLabels:
      app.kubernetes.io/name: cloud-diplomats-api
      app.kubernetes.io/component: api
