apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloud-diplomats-rollout

resources:
  - ../../../../applications/base/cloud-diplomats-rollout/rbac
  - ../../../../applications/base/cloud-diplomats-rollout/api
  - ../../../../applications/base/cloud-diplomats-rollout/ingress

