apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloud-diplomats-api-micrometer
  namespace: cloud-diplomats
  labels:
    prometheus.io/scrap-with: kube-prometheus-stack

    app.kubernetes.io/instance: cloud-diplomats-app
    app.kubernetes.io/component: api
    app.kubernetes.io/application: cloud-diplomats-api-micrometer
    app.kubernetes.io/managed-by: Jonathan

spec:
  endpoints:
    - interval: 30s
      port: metrics
      path: /actuator/prometheus
      # Do not remove targetLabel: component and application as they are used in Grafana dashboard
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_label_app_kubernetes_io_application]
          targetLabel: application
        - sourceLabels: [__meta_kubernetes_pod_label_app_kubernetes_io_component]
          targetLabel: component
        - sourceLabels: [__meta_kubernetes_pod_label_app_kubernetes_io_managed_by]
          targetLabel: managed_by

  namespaceSelector:
    matchNames:
      - cloud-diplomats

  selector:
    matchLabels:
      app.kubernetes.io/instance: cloud-diplomats-app
      app.kubernetes.io/component: api
      app.kubernetes.io/application: cloud-diplomats-ap-micrometeri