apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: microservice-webhook
  namespace: notification
  labels:
    prometheus.io/scrap-with: kube-prometheus-stack
spec:
  endpoints:
    - interval: 30s
      port: metrics
      path: /actuator/prometheus

  namespaceSelector:
    matchNames:
      - notification
  selector:
    matchLabels:
      app.kubernetes.io/component: microservice
      app.kubernetes.io/name: microservice-webhook
