apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spring-namespace-reader

rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]
