apiVersion: v1
kind: Service

metadata:
  name: hello-world
  namespace: cloud-diplomats

spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: container-port

  selector:
    app.kubernetes.io/component: microservice
    app.kubernetes.io/name: hello-world