apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloud-diplomats-rollout

resources:
  - pdb.yaml
  - deployment.yaml
  - secret.yaml
  - service.yaml
  - service-monitor.yaml
