apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloud-diplomats-rollout

resources:
  - pdb.yaml
  - rollout.yaml
  - secret.yaml
  - service-stable.yaml
  - service-canary.yaml
  - service-monitor.yaml
