apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api
  namespace: cloud-diplomats-rollout
  labels:
    prometheus.io/scrap-with: kube-prometheus-stack
spec:
  endpoints:
    - interval: 10s
      port: metrics
      path: /actuator/prometheus
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_label_app_kubernetes_io_application]
          targetLabel: application
        - sourceLabels: [__meta_kubernetes_pod_label_app_kubernetes_io_component]
          targetLabel: component
        - sourceLabels: [__meta_kubernetes_pod_label_app_kubernetes_io_managed_by]
          targetLabel: managed_by

  namespaceSelector:
    matchNames:
      - cloud-diplomats-rollout

  selector:
    matchLabels:
      app.kubernetes.io/application: cloud-diplomats-api
      app.kubernetes.io/component: api