apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webhook
  namespace: argocd
  annotations:
    # ArgoCD image updater configuration
    argocd-image-updater.argoproj.io/image-list: "wb=jojoooo1/microservice-webhook"
    argocd-image-updater.argoproj.io/wb.update-strategy: latest

    argocd-image-updater.argoproj.io/write-back-target: kustomization # Note: do not use argocd or it will conflict with envsubst
    argocd-image-updater.argoproj.io/write-back-method: git

  # Add this finalizer ONLY if you want these to cascade delete (A cascade delete, deletes both the app and its resources, rather than only the app.)
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
  
spec:
  project: default

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
  source:
    repoURL: https://github.com/Jojoooo1/argo-deploy-applications.git
    targetRevision: main
    path: overlays/local/applications/webhook
    # Note: envsubst envs are injected through parent app via helm chart in tf.
    plugin:
      name: envsubst
      env:
        - name: ENV
          value: "${ARGOCD_ENV_ENV='local'}"

        - name: DNS
          value: "${ARGOCD_ENV_DNS='local'}"

        - name: PROJECT
          value: "${ARGOCD_ENV_PROJECT='sandbox'}"

  destination:
    server: https://kubernetes.default.svc
    namespace: default
